py_binary(
    name = "coverage",
    srcs = ["coverage.py"],
    data = [
        "@lcov//:lcov_files",
        "@rules_perl//perl:current_exec_toolchain",
    ],
    visibility = ["//visibility:public"],
    deps = [],
)
