load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "figure",
    hdrs = [
        "canvas_api.h",
        "canvas_ppm_backend.h",
        "data_saver.h",
        "figure.h",
        "file_handler.h",
        "interfaces.h",
        "rgb_color.h",
    ],
    visibility = ["//visibility:public"],
)
